services:
  app:
    container_name: creations_react
    image: creations_react_img
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - creations_network
    volumes:
      - ./../creations_volume/nginx/conf.d:/etc/nginx/conf.d

networks:
  creations_network:
    external: true
