services:
  app:
    container_name: creations_react
    image: creations_react_img
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - creations_network

networks:
  creations_network:
    external: true
